# Discord Weather Bot Prometheus設定
# メトリクス収集とアラート設定

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'discord-weather-bot'

# アラートルール設定
rule_files:
  - "alert_rules.yml"

# アラートマネージャー設定
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# スクレイプ設定
scrape_configs:
  # Prometheus自体の監視
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Discord Weather Bot の監視
  - job_name: 'discord-weather-bot'
    static_configs:
      - targets: ['weather-bot:9090']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  # PostgreSQL の監視
  - job_name: 'postgres'
    static_configs:
      - targets: ['db:5432']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Redis の監視
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Nginx の監視
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:80']
    metrics_path: '/nginx_status'
    scrape_interval: 30s

  # Node Exporter（システムメトリクス）
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s

  # cAdvisor（コンテナメトリクス）
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 30s