"""Create users table

Revision ID: 60012a39537d
Revises: 
Create Date: 2025-07-20 17:08:29.080645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60012a39537d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('discord_id', sa.BigInteger(), nullable=False),
    sa.Column('area_code', sa.String(length=10), nullable=True),
    sa.Column('area_name', sa.String(length=100), nullable=True),
    sa.Column('notification_hour', sa.Integer(), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('is_notification_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_discord_id'), 'users', ['discord_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_discord_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
